---
apiVersion: v1
kind: Service
metadata:
  name: firefox01-service
spec:
  type: NodePort
  ports:
    - name: firefox-tcp-vnc
      port: 5900
      protocol: TCP
      nodePort: 31001
      targetPort: firefox-tcp-vnc
  sessionAffinity: None
