---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak6
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      hostNetwork:  true
      containers:
        - name: teamspeak6
          image: teamspeaksystems/teamspeak6-server:v6.0.0-beta8
          envFrom:
            - configMapRef:
                name: teamspeak-env
          volumeMounts:
          - mountPath: /var/tsserver/
            name: teamspeak-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - zbox
      dnsPolicy: ClusterFirst
      volumes:
      - name: teamspeak-volume
        nfs:
          server: 192.168.1.10
          path: /mnt/volumes/nfs/teamspeak6/server
          readOnly: false
