---
apiVersion: v1
kind: Service
metadata:
  name: firefox2-service
spec:
  type: NodePort
  ports:
    - name: firefox-tcp-web
      port: 5800
      protocol: TCP
      targetPort: firefox-tcp-web
      nodePort: 30001
    - name: firefox-tcp-vnc
      port: 5900
      protocol: TCP
      nodePort: 30002
      targetPort: firefox-tcp-vnc
  sessionAffinity: None
